### PR TITLE
Tweak ui

### PR DESCRIPTION
**Pull request by MjnMixael**
This should take care of the most pressing UI issues. I'm not sure I like the gradient on the tabs because we don't use a gradient anywhere else.. but it's the best I could come up with at 1am!

### CODE REVIEW

**Comment by ngld** [comment]
Looks great! To move the buttons you first have to increase the column width (`.logo-box` in `style.css`) and remove one `<br>` tag.

Regarding the scrolling mod title: You [can do it without JS](https://jsfiddle.net/jonathansampson/XxUXD/) unless I misunderstood what you meant...

**Comment by MjnMixael** [comment]
I can easily translate the text without JS, but I need JS to fetch the text length. Then we should only translate the text IF there is overflow and we should only translate it for the needed amount. Something we can tackle later on... but I added the P tags so that it will be simpler when we get there.

**Comment by ngld** [comment]
Alright, I see what you mean. Is this ready for merging or do you want to change something else?

**Comment by MjnMixael** [comment]
Lemme add the button re-ordering as you just suggested, then I'll be done for the night! 5 minutes.

**Comment by MjnMixael** [comment]
Now I'm done!

**Comment by ngld** [comment]
Merged! Only issue I could fine was that the tabs from the two tab bars don't align. It's caused by the fact that the first bar has spaces between the tabs and the second doesn't.

I don't think I can fix this in the template but I'll look into it.

**Pull request merged**
