### PR TITLE
Tweak ui

### PR DESCRIPTION
**Pull request by MjnMixael**
…ticularly the Details page and dev pages. Final retail banner also included.

I was not able to fix the issue where a window width smaller than 1053 pixels causes Dev Tabs to start to disappear. However, we might consider making 1116 the minimum window width, if possible, simply because smaller than that and things just start getting out of place all over the UI.

### CODE REVIEW

**Comment by MjnMixael** [comment]
Additionally, the mod-banner sizing causes an issue where if there is not mod-banner, you can't even see the mod version. Can we use python to do something like IF=mod.banner class="img-frame" ELSE class="img-frame-empty"?

**Comment by ngld** [comment]
We can do that in the template: `<div :class="mod.banner ? 'mod-banner' : 'mod-banner-empty'">`

**Comment by MjnMixael** [comment]
Excellent, I'll do that right quick then.

**Comment by MjnMixael** [comment]
Except.. actually I just get stupid when I work on things this late.. which means this fixes the problem more simply and I should just go to bed.

**Comment by ngld** [comment]
Thanks, rest well. :)

**Pull request merged**
